name = "cyxclub-api"
main = "workers/api.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "cyxclub_db"                              # Workers 代码里用 env.cyxclub_db 访问
database_name = "cyxclub-db"
database_id = "e9c8b31e-80a6-4b0a-8023-64ce0ff22f11"
