-- CYX Club Database Schema for Cloudflare D1

-- 卡密表 (generated by customer service)
CREATE TABLE IF NOT EXISTS card_keys (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  card_key TEXT UNIQUE NOT NULL,
  used INTEGER DEFAULT 0,
  used_by TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  used_at DATETIME
);

-- 卡密表 (管理员通过后台生成，用户注册时使用)
CREATE TABLE IF NOT EXISTS card_keys (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  card_key TEXT UNIQUE NOT NULL,
  used INTEGER DEFAULT 0,
  used_by TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  used_at DATETIME
);

-- 商品表 (客服配置的服务商品)
CREATE TABLE IF NOT EXISTS products (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 用户表
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  card_key TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 员工/打手表
CREATE TABLE IF NOT EXISTS employees (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  display_name TEXT NOT NULL,
  game_types TEXT, -- JSON array of games they handle
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 订单表
CREATE TABLE IF NOT EXISTS orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  game TEXT NOT NULL,
  service_type TEXT NOT NULL,
  employee_id INTEGER NOT NULL,
  details TEXT, -- JSON: account info, requirements etc
  status TEXT DEFAULT 'pending', -- pending, accepted, in_progress, completed, cancelled
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (employee_id) REFERENCES employees(id)
);

-- Seed admin account (password: cyx2026admin)
-- The password hash below is PBKDF2 with the format: salt:hash
-- This will be generated during first deployment or manually
-- For now, insert a placeholder that must be updated after deployment
-- Run: wrangler d1 execute cyx-club-db --file=schema.sql
-- Then update admin password via a one-time script or the admin password reset
INSERT OR IGNORE INTO users (username, password_hash, card_key)
VALUES ('admin', 'PLACEHOLDER_UPDATE_AFTER_DEPLOY', 'ADMIN_SEED');
